### ISSUE TITLE
does this mod support 1.16.3?

### ISSUE THREAD

**Issue by ghost** [Draylar/tiered#10]
and if it doesn't officially, would it work if i just changed the mod properties to "support" it, or is there code that needs to be updated between versions

**Comment by Draylar** [comment]
no and no, Mojang did some big refactoring to the attribute system in 1.16. A fair amount of work is needed for an update (I am 75%~ done but it will be a while before release), with the difficult stuff being related to attributes displaying on tooltips.

**Comment by NameLord** [comment]
Request closing this issue
