### ISSUE TITLE
Doesn't work with some mods adding tools and armor.

### ISSUE THREAD

**Issue by K0-RR** [Draylar/tiered#12]
[Astromine](https://www.curseforge.com/minecraft/mc-mods/astromine-main) and [Mythic Metals](https://www.curseforge.com/minecraft/mc-mods/mythicmetals) work fine but your mod - Vanilla Toolsets, - [Terran Expansion](https://www.curseforge.com/minecraft/mc-mods/terran-expansion), [Better Nether](https://www.curseforge.com/minecraft/mc-mods/betternether), [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) and [EETM](https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric) does not.

Also how to disable some of the modifiers? Eg. +10 health points from legendary weapons. For now I changed the amount value for all files in /data/tiered/item_attributes/all/ in the attribute below to zero. Can I just delete this part of the code?
```
{
      "type": "generic.max_health",
      "modifier": {
        "name": "tiered:rare",
        "operation": "ADDITION",
        "amount": 0
      },
      "optional_equipment_slots": [
        "MAINHAND",
        "FEET",
        "LEGS",
        "CHEST",
        "HEAD"
      ]
```

**Comment by K0-RR** [comment]
Oh and your main GitHub page lacks information about the Tiered mod

**Comment by Draylar** [comment]
Mods need to add their tools to the respective tags inside the `fabric` namespace (`fabric:pickaxes`, `fabric:chestplates`, `fabric:shovels`, etc.), or you can add the tools to the tags through your own datapack. If you don't want the attribute bonus, you can simply delete it from the `attributes` list.
