### ISSUE TITLE
Attributes don't display on a dedicated client

### ISSUE THREAD

**Issue by Draylar** [Draylar/tiered#2]
My guess is that attribute data (`AttributeDataLoader`) isn't synced to the client, so no attributes display on tooltips. Not sure how I'd like to fix this yet.

**Comment by N1ckn1ght** [comment]
still not fixed sadly(

**Comment by Draylar** [comment]
I've started a fix in 1.1.0 beta ([GitHub](https://github.com/Draylar/tiered/releases/tag/1.1.0-beta_1.15.2), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/tiered/files/2970509)). This should mostly work, but it was a huge update, so I expect things to break.
