### ISSUE TITLE
Forge server crashing on startup

### ISSUE THREAD

**Issue by Camperspro** [Draylar/tiered#35]
![Crash](https://user-images.githubusercontent.com/61707333/114341381-a178a400-9b27-11eb-92eb-f2679f9c6336.png)

**Comment by Cixon** [comment]
Ah, you beat me to it. Had this same issue on my server. This should be a easy fix.

**Comment by Draylar** [comment]
This is the Fabric repository of Tiered; I'm not associated with the Forge port. I think you'll have to contact the other author on CF.
