### ISSUE TITLE
crash with carpet mod

### ISSUE THREAD

**Issue by DbpGaming** [Draylar/tiered#5]
crash report - https://pastebin.com/QmkuWZAH
version - 1.1.0-beta

seems like a mixin conflict

**Comment by Draylar** [comment]
This is an incompatibility between [Reach Entity Attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) and [Carpet](https://github.com/gnembon/fabric-carpet). Carpet seems to [put a mixin at this same area](https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/mixins/ServerPlayerInteractionManager_antiCheatMixin.java) for some sort of anti-cheat.

Between the two, I would say this falls more on Carpet to fix. There isn't much I can do about it.

**Comment by DbpGaming** [comment]
sorry for the late response, just opened an issue on carpet, i didn't realize it was conflicting with a embed library and not tiered, thank you for the quick response even though i was late
