### ISSUE TITLE
Weird visual issue

### ISSUE THREAD

**Issue by DanShu15** [Draylar/tiered#7]
So with 1.16 around the corner I hadn't got to configuring or changing anything with Tiered quite yet, I just popped it back in for me to work on later.
We've never been able to see tiered info on any of our items, and I assumed that would be fixed when I did get around to configuring it. For some reason today 1 of our players can see tiered info on almost all items. The rest of us can see NBT tags, but not the info (F3+H debug view enabled for the NBT tags).
We're all using a clone of the same install through MultiMC, and before server restart it didn't work for him either.

Is there a hotkey I've accidentally toggled that he's untoggled?
Screenshots with labels:
https://imgur.com/a/eOirY8x

Edit- Interesting, it seems to work just fine in single player with the same client
Edit2- Even more interesting, now it works online LOL Something about making an item in single player then connecting cleared it up
Edit3- So if I restart and go direct to multiplayer then I can't see Tiered info, but if I go into single-player and mouse over a player-crafted item it works fine in both single and multiplayer until I exit minecraft and start it back up again

**Comment by Draylar** [comment]
Aguuhhh, this sounds fun. I'll look into it once I get into updating this to 1.16 fully.

**Comment by DanShu15** [comment]
our new motto's going to be "You Make It - We Break it"
